[mypy]
python_version = 3.12
plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin
strict = True
warn_unused_ignores = True
warn_return_any = True
disallow_untyped_defs = True
files = src, tests

[mypy-testcontainers.*]
ignore_missing_imports = True
